-- Safe RLS disable: ALL statements wrapped to handle missing tables
-- Run this in Supabase SQL Editor

-- 1. Drop all RLS policies (safe - skips if table/policy doesn't exist)
DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can insert profiles" ON public.profiles; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can read profiles" ON public.profiles; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "Users can view their couples" ON public.couples; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can update their couples" ON public.couples; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can insert couples" ON public.couples; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can view couples" ON public.couples; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can insert couples" ON public.couples; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can update couples" ON public.couples; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "Users can view memories of their couples" ON public.memories; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can modify memories of their couples" ON public.memories; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can view memories" ON public.memories; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can insert memories" ON public.memories; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can update memories" ON public.memories; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can delete memories" ON public.memories; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "Users can view events of their couples" ON public.events; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can modify events of their couples" ON public.events; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can view events" ON public.events; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can insert events" ON public.events; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can update events" ON public.events; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can delete events" ON public.events; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "Users can view goals of their couples" ON public.goals; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can modify goals of their couples" ON public.goals; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can view goals" ON public.goals; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can insert goals" ON public.goals; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can update goals" ON public.goals; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can delete goals" ON public.goals; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "Users can view notes of their couples" ON public.notes; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can modify notes of their couples" ON public.notes; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can view notes" ON public.notes; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can insert notes" ON public.notes; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can update notes" ON public.notes; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can delete notes" ON public.notes; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "Users can view lists of their couples" ON public.lists; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can modify lists of their couples" ON public.lists; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can view lists" ON public.lists; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can insert lists" ON public.lists; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can update lists" ON public.lists; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can delete lists" ON public.lists; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "Users can view mood settings of their couples" ON public.mood_settings; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can modify mood settings of their couples" ON public.mood_settings; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can view mood settings" ON public.mood_settings; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can insert mood settings" ON public.mood_settings; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can update mood settings" ON public.mood_settings; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "Users can view period entries of their couples" ON public.period_entries; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can modify their own period entries" ON public.period_entries; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can view period entries" ON public.period_entries; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can insert period entries" ON public.period_entries; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can update period entries" ON public.period_entries; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can delete period entries" ON public.period_entries; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "Users can view questions of their couples" ON public.questions; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can modify questions of their couples" ON public.questions; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can view questions" ON public.questions; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can insert questions" ON public.questions; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can update questions" ON public.questions; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can delete questions" ON public.questions; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "Users can view answers of their couples" ON public.answers; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can insert their own answers" ON public.answers; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can view answers" ON public.answers; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can insert answers" ON public.answers; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "Users can view surprises of their couples" ON public.surprises; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Users can modify surprises of their couples" ON public.surprises; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can view surprises" ON public.surprises; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can insert surprises" ON public.surprises; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can update surprises" ON public.surprises; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN DROP POLICY IF EXISTS "Anyone can delete surprises" ON public.surprises; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

-- 2. Drop foreign key constraints (all wrapped in safe blocks)
DO $$ BEGIN BEGIN ALTER TABLE public.couples DROP CONSTRAINT IF EXISTS couples_user1_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.couples DROP CONSTRAINT IF EXISTS couples_user2_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.memories DROP CONSTRAINT IF EXISTS memories_couple_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.events DROP CONSTRAINT IF EXISTS events_couple_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.goals DROP CONSTRAINT IF EXISTS goals_couple_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.notes DROP CONSTRAINT IF EXISTS notes_couple_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.notes DROP CONSTRAINT IF EXISTS notes_created_by_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.lists DROP CONSTRAINT IF EXISTS lists_couple_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.mood_settings DROP CONSTRAINT IF EXISTS mood_settings_couple_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.period_entries DROP CONSTRAINT IF EXISTS period_entries_user_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.period_entries DROP CONSTRAINT IF EXISTS period_entries_couple_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.questions DROP CONSTRAINT IF EXISTS questions_couple_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.answers DROP CONSTRAINT IF EXISTS answers_question_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.answers DROP CONSTRAINT IF EXISTS answers_user_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.surprises DROP CONSTRAINT IF EXISTS surprises_couple_id_fkey; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

-- 3. Disable RLS on all tables (all wrapped in safe blocks)
DO $$ BEGIN BEGIN ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.couples DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.memories DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.events DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.goals DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.notes DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.lists DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.moods DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.mood_settings DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.period_entries DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.questions DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.answers DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN ALTER TABLE public.surprises DISABLE ROW LEVEL SECURITY; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;

-- 4. Drop old policies and triggers
DO $$ BEGIN BEGIN DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- 5. Grant permissions (safe even if no tables exist)
DO $$ BEGIN BEGIN GRANT ALL ON ALL TABLES IN SCHEMA public TO anon; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated; EXCEPTION WHEN OTHERS THEN NULL; END; BEGIN GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated; EXCEPTION WHEN OTHERS THEN NULL; END; END $$;